version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: projectcam-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: projectcam
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - projectcam-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: projectcam-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/projectcam?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - ./uploads:/app/uploads
    networks:
      - projectcam-network

  nginx:
    image: nginx:alpine
    container_name: projectcam-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
    networks:
      - projectcam-network

volumes:
  mongodb_data:

networks:
  projectcam-network:
    driver: bridge
